### ISSUE TITLE
Where to pass in additional network info?

### ISSUE THREAD

**Issue by isaacsas** [JuliaDiffEq/DiffEqJump.jl#23]
The last thing we would need to support other SSAs is a mechanism for passing in additional network info (for example, a jump dependency graph). 

For pure `MassActionJump` systems this actually doesn't need to be passed in; the jump type stores everything that is needed to build a dependency graph. So this could just be handled with the `aggregate` or `initialize` routines for a specific SSA. That said, if we allow it to be passed in it should be possible for a number of the new SSAs to support both `MassActionJumps` and `ConstantJumps`. While I don't myself need non-mass action systems, I like the idea of supporting both jump types within as many of the new SSAs as possible.

I see a few ways this could be handled; having the new SSA aggregator algorithms take this info as parameters when constructed, or extending `JumpProblem` to forward named arguments to `aggregate` and letting the specialized `aggregate` define parameter fields for the needed network info. But maybe there is a better way to handle this?

Then we could set everything up so that for a pure mass-action system everything is calculated for users, but for a hybrid system they are required to pass the necessary additional SSA info.

**Comment by isaacsas** [comment]
I went with passing additional SSA specific information through the `JumpProblem`.

Closed by [#24](https://github.com/JuliaDiffEq/DiffEqJump.jl/pull/24)

**Comment by ChrisRackauckas** [comment]
I'm kind of thinking it should be through the aggregator type though. For the rest of DiffEq, the algorithms take their additional args while the kwargs are common across all algorithms. For example, `Rosenbrock23(autodiff=false)` passes autodiff controls to `Rosenbrock`.

**Comment by isaacsas** [comment]
I actually think switching function wrappers to be configured as you suggest might be a good idea too (with a flag to the algorithm). It seemed more in the spirit of what you do for the ODE methods. Using functionwrappers is really a choice about configuration of the algorithm implementation, not an entirely new choice of SSA. 

NRM and other optimized SSAs generally need info about connectivity between the jumps (or species involved in the jumps). It seemed to make sense to also pass that info in when one passes in the jumps (i.e. through the `JumpProblem`). This way if someone changes the set of jumps they'll have to also pass a new set of the jump dependency parameters (and not accidentally pass an old instance of the algorithm with old values for them). This info might also be needed / desirable to have in other contexts (like hybrid algorithms).

Maybe it makes sense to make a distinction between "numerical" algorithm parameters (which should go through the algorithm constructor) and "jump"-connectivity parameters (which go through the`JumpProblem`)? 

With that said, I think either way works fine, and would be happy to change it if you want to stick with passing everything through the algorithm. Let me know your preference and I can tweak it this weekend.

**Comment by isaacsas** [comment]
Closing as I settled on passing through the jump problem constructor.
