### ISSUE TITLE
Solving JumpProblem with EM() produces strange discontinuities after jump

### ISSUE THREAD

**Issue by onoderat** [JuliaDiffEq/DiffEqJump.jl#39]
The following kinds of output is produced when solving JumpProblems with the EM() solver. 

<img width="680" alt="screen shot 2018-04-27 at 4 11 39 am" src="https://user-images.githubusercontent.com/8842263/39359987-24cbed40-49d1-11e8-95a5-d68be2b1865e.png">

This is clearly wrong as the solution jumps again after the jump of sets u to 0. I did check that this problem went away when the recommended SRIW1 solver was used instead (output is below). 

![image](https://user-images.githubusercontent.com/8842263/39360143-e7a91644-49d1-11e8-9e44-4bc0e9de1f4c.png)

The minimal working example that generated the plots is the following
```
using DifferentialEquations

rate(u,p,t) = 5
affect!(integrator) = (integrator.u[1] = 0.0)
jump = VariableRateJump(rate,affect!)

function f(du,u,p,t)
  du[1] = 0.
end
function g(du,u,p,t)
  du[1] = 0.05
end
prob = SDEProblem(f,g,[0.0],(0.0,1.0))

jump_prob = JumpProblem(prob,Direct(),jump)
sol_EM = solve(jump_prob, EM(), dt=0.5e-3, adaptive=false, seed=1);
sol_SRI = solve(jump_prob, SRIW1(), dt=0.5e-3, adaptive=false);

using Plots
plot(sol_EM, linewidth=1)
plot(sol_SRI, linewidth=1)

```

**Comment by ChrisRackauckas** [comment]
Thanks. Nice MWE. Fixed here:

https://github.com/JuliaDiffEq/DiffEqNoiseProcess.jl/commit/0a688e828cca1482812dbae416ba37c8ef2cf32c

Patch tag incoming. It's a bug that only showed up for fixed timestep methods with event handling, so that's quite deep!
