### ISSUE TITLE
Jump PDEs

### ISSUE THREAD

**Issue by elevien** [JuliaDiffEq/DiffEqJump.jl#6]
Any plans for Jump PDEs? Here are some typical problems: [arXiv:1602.07398](https://arxiv.org/abs/1602.07398). I haven't looked too closely at the PDE code, but callbacks are not yet implemented for PDEs, right?

**Comment by ChrisRackauckas** [comment]
Well, the PDE part needs a re-design. Instead of being special-cased, it just needs to internally discretize and use the ODE/SDE/DAE/DDE solvers. Then all of the extra stuff will come for free through abstract typing.

**Comment by ChrisRackauckas** [comment]
The PDE design makes it so that way specifically targetting PDEs won't be necessary: it will be free.
