### ISSUE TITLE
Jump Diffusion Monte Carlo simulations:  the first jump occurs in the same time

### ISSUE THREAD

**Issue by SSkor** [JuliaDiffEq/DiffEqJump.jl#68]
discussion [here](https://discourse.julialang.org/t/jump-diffusion-process-when-does-a-jump-occur/22837/5)
`rate(u,p,t) = 2
affect!(integrator) = (integrator.u[1] = integrator.u[1]/2)
jump = VariableRateJump(rate,affect!)
jump_prob = JumpProblem(prob,Direct(),jump)
monte_prob = MonteCarloProblem(jump_prob)
sol = solve(monte_prob,SRIW1(),num_monte=3,parallel_type=:none,dt=0.001,adaptive=false)`

**Comment by ChrisRackauckas** [comment]
What's a `prob` for this that recreates the issue? When making an issue, it's good to always make it a self-contained "copy-pastable" example that can be ran.

**Comment by SSkor** [comment]
```
function f(du,u,p,t)
  du[1] = u[1]
end
function g(du,u,p,t)
  du[1] = u[1]
end
prob = SDEProblem(f,g,[1.0],(0.0,1.0))
rate(u,p,t) = 2
affect!(integrator) = (integrator.u[1] = integrator.u[1]/2)
jump = VariableRateJump(rate, affect!, save_positions=(false,false))
jump_prob = JumpProblem(prob,Direct(),jump)
monte_prob = MonteCarloProblem(jump_prob)
sol = solve(monte_prob,SRIW1(),num_monte=3,parallel_type=:none,dt=0.001,adaptive=false)
```

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaDiffEq/DiffEqJump.jl/commit/950114e52014d9ecf48cbbbd96f7092bb71573b2
