### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqJump.jl#73]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()
